# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Containment Man"
tab_title: Four Frame OneShot! #This text shows up on the browser tab
email:
description: "Containment Man: Last Stand Of The Amanaza, is a post-apocalyptic one shot about the aftermath of an assymetric civil war involving Nuclear Terrorism. Here a young man remembers what led him to eventually moving to the Japanese controlled region of California."
url: "https://lwflouisa.github.io/ContainmentMan/" # the base hostname & protocol for your site

# Comic Social Media
twitter_username: https://twitter.com/FlouisaLW
tumblr_username: 
patreon_username: 

# Author Social Media
author_twitter_username: https://twitter.com/ToDiaspora
author_tumblr_username:
author_patreon_username:



# Build settings
markdown: kramdown
theme: minima
